#!/bin/bash
echo "Change owner and group of all files and directories:"; find . -type f -exec chown vincent '{}' \; -exec chgrp staff '{}' \; -o -type d -exec chown vincent '{}' \; -exec chgrp staff '{}' \;
